name: Automerge and Assign Reviewers

on:
  pull_request:
    types:
      - opened
      - synchronize

  check_run:
    types:
      - completed
  check_suite:
    types:
      - completed
  status: {}

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Raaj and Jaden as reviewer
        uses: kentaro-m/auto-assign-action@v1.2.5
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}