name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag in env variable
        run: |
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "${{ secrets.DOCKER_USER }}/${{ secrets.REPOSITORY_NAME }}" > APP_NAME
          echo "$GITHUB_SHA" > TAG
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $(cat APP_NAME):$(cat TAG)
      - name: Tag the image to latest
        run: docker tag $(cat APP_NAME):$(cat TAG) $(cat APP_NAME):$(cat TAG)
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Image push
        run: docker push $(cat APP_NAME):latest
