name: Check eslint

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    branches:
      - '*'

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run eslint
        run: yarn lint
      - name: Test build
        run: yarn build
